parameters:
#    acme_calculator.example.class: Acme\CalculatorAPIBundle\Example

services:
#    acme_calculator.example:
#        class: %acme_calculator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
