acme_calculator_homepage:
    path:     /
    defaults: { _controller: AcmeCalculatorBundle:Default:index }

acme_calculator_compute:
    path:     /compute
    defaults: { _controller: AcmeCalculatorBundle:Default:compute }
